[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
soldare = "HTiYVYKAGyZptRer8Q3HGZY3ghjm5fo15BVwk7NtWyuA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
